services: 
  redis:
    container_name: "koishibot-redis"
    restart: unless-stopped
    image: "redis"
    volumes:
      - "koishibot-data:/data"
  hamdle-web:
    container_name: "koishibot-web"
    restart: unless-stopped
    image: ghcr.io/koishibuh/koishibot-web:1.0.0
    env_file:
      - ~/docker-env/.koishibot-env
    ports:
      - 8086:8080
    depends_on: 
      redis:
        condition: service_started
volumes:
  koishibot-data: